# Generated by Django 5.2.3 on 2025-06-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games_Database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='category',
            field=models.CharField(default='ps4', max_length=5),
        ),
    ]
