# Generated by Django 5.1.3 on 2025-07-31 01:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games_Database', '0005_discussion_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discussion',
            new_name='reply',
        ),
    ]
