# Generated by Django 5.1.3 on 2025-07-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games_Database', '0006_rename_discussion_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.CharField(default='ps4', max_length=25),
        ),
    ]
